name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Repository name to create"
        required: true
      repo_description:
        description: "Description name to create"
        default: ""
      visibility:
        description: "Repository visibility (public/private)"
        required: true
        type: choice
        options:
          - public
          - private
        default: "public"

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        run: terraform -chdir=src/terraform init

      - name: Terraform Validate
        run: terraform -chdir=src/terraform validate

      - name: Terraform Apply
        run: terraform -chdir=src/terraform apply -auto-approve
        env:
          TF_VAR_github_token: ${{ secrets.GH_PAT }}
          TF_VAR_github_owner: ${{ vars.ORG_NAME }}
          TF_VAR_repo_name: ${{ inputs.repo_name }}
          TF_VAR_repo_description: ${{ inputs.repo_description }}
          TF_VAR_visibility: ${{ inputs.visibility }}